import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ApolloWrapper } from "@/lib/apollo-wrapper";
import GlobalConfigProvider from "@/lib/GlobalConfigProvider";
import HomeLayout from "./HomeLayout";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-300 p-2`}
      >
        <GlobalConfigProvider>
          <AntdRegistry>
            <ApolloWrapper>
              <HomeLayout>
                {children}
              </HomeLayout>
            </ApolloWrapper>
          </AntdRegistry>
        </GlobalConfigProvider>
      </body>
    </html>
  );
}
